### PR TITLE
Add jsonx as FileExtension

### PR DESCRIPTION
**Pull request by deveth0**

### CODE REVIEW

**Comment by stefanseifert** [comment]
if we add this here, we have to add it in the aem-definitions rules for dispatcher as well.

but i'm not sure if it's a good idea:
1. why need a new extension jsonx? you can also use htx with the json content type
2. looking back i'm not totally happe introducing the htx concept at all - it is a special solution which should normally by solved by HTTP standard ways only (appropriate caching header, which have to be sent with the response anyway plus the special dispatcher non-caching header).

so i'm not so keen to extending to jsonx. maybe we should deprecate the htx extension instead.

**Comment by deveth0** [comment]
Fair enough, we currently mostly use the jsonx extension to make clear, that the response is a json format (mostly convenience), so we could change it to htx too. 

I agree, that the usage of a "hack" like htx is the right approach to solve the caching issues but on the other hand this provides an additional fallback if something is missing in your code. Furthermore this makes it possible to ensure that all htx resources are uncached by additionally setting the caching header in the dispatcher configuration.

**Comment by stefanseifert** [comment]
globally ignoring caching for htx in dispatcher is somewhat a false sense of security - if the code forgets to set the proper caching header they may still be cached by CDNs or proxies/browser cache on the customers side.

**Comment by deveth0** [comment]
Sorry, my fault. I did not simply mean "disable caching" but setting the headers in Apache:
```
<LocationMatch "^.*\.(jsonx)$">
Header set Cache-Control "private, no-store, max-age=0"
</LocationMatch>
```

**Comment by mrozati** [comment]
Another idea would be to use a selector instead of changing extension. e.g. 'nocache.json' or 'nocache.html'
If the resources are in a specific path you could also use the mod_rewrite to prevent requests without 'nocache' selector e.b. by redirecting them to those with 'nocache' selector

**Pull request closed without merging**
